### ISSUE TITLE
Saved 0 entries

### ISSUE THREAD

**Issue by capocasa** [jonthysell/HawDict#2]
Latest version on linux says "saved 0 results" for each dictionary, perhaps a change of URL is needed?

Thanks for making this!

Carlo

**Comment by jonthysell** [comment]
Thanks, it looks like they've completely redesigned the site to be more PDF focused. I'll have to see if I can access the original HTML-based contents.

**Comment by capocasa** [comment]
Thanks for replying! That'd be amazing.

**Comment by jonthysell** [comment]
It looks like the Wayback Machine has archived *some* of the URLs, but not all of them. And there's slight differences in the pages that are saved, meaning I'll have to tweak the processing and cleanup.

Thankfully I have a private cache of the input and output files from each version of HawDict, so I should be able to switch to the existing archive URLs to clean up them up and make sure I get the same output.

But I'm really kicking myself for not ensuring that the URLs were scanned into the Wayback Machine sooner, and pointing my tool at those, rather than the live URLs which have changed slightly over the years.

**Comment by jonthysell** [comment]
Please try again with HawDict v0.15.0. I've gotten it working again by switching to using alternative URLs via the Wayback Machine, so hopefully this code will be functional for much longer. Also found some extra 18 words that weren't getting processed correctly in previous versions.
